apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      labels: {}
      name: "hello-world"
    spec:
      selector:
        app: "hello-world"
      type: LoadBalancer
      ports:
        - name: http
          port: 8080
          targetPort: 8080
          nodePort: 32000
          protocol: TCP
  - apiVersion: "apps/v1"
    kind: "Deployment"
    metadata:
      labels:
        app: "hello-world"
        version: "1.0.0"
      name: "hello-world"
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: "hello-world"
          version: "1.0.0"
      template:
        metadata:
          labels:
            app: "hello-world"
            version: "1.0.0"
        spec:
          containers:
            - image: "sivaiah/python-hello-world:latest"
              name: "hello-world"
              resources:
                limits:
                  cpu: 500m
                requests:
                  cpu: 200m
              ports:
                - protocol: TCP
                  containerPort: 8080
